fix typos
arzg/website pull request #17
Opened 2024-12-30 15:24 UTC by thiishfuoqdsjnfk

Found with

cargo install typos

typos --exclude content/vector-types.md --exclude .ontent/n-times-faster.md

2025-01-04 12:06 UTC, lunacookies requested changes

2025-01-04 12:06 UTC, lunacookies commented on content/clang-vectors.md
> +and Homogeneous Short-Vector Aggregates” (HVAs).
Seems like the spell checker removed the curly quotes here for some reason. Apart from that, LGTM!

2025-01-05 11:45 UTC, thiishfuoqdsjnfk commented on content/clang-vectors.md
> +and Homogeneous Short-Vector Aggregates” (HVAs).
fixed :)

2025-01-05 13:45 UTC, merged

2025-01-05 13:45 UTC, lunacookies commented
Thanks!